/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/o46GGKiSBpm
 */
import Link from "next/link"
import { NavigationMenuLink, NavigationMenuList, NavigationMenu } from "@/components/ui/navigation-menu"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <header className="flex h-20 w-full items-center px-4 md:px-6">
      <Link className="mr-6 hidden lg:flex" href="#">
        <MountainIcon className="h-6 w-6" />
        <span className="sr-only">ShadCN Inc</span>
      </Link>
      <NavigationMenu className="hidden lg:flex">
        <NavigationMenuList>
          <NavigationMenuLink asChild>
            <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
              Home
            </Link>
          </NavigationMenuLink>
          <NavigationMenuLink asChild>
            <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
              About
            </Link>
          </NavigationMenuLink>
          <NavigationMenuLink asChild>
            <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
              Services
            </Link>
          </NavigationMenuLink>
          <NavigationMenuLink asChild>
            <Link className="flex w-full items-center py-2 text-lg font-semibold" href="#">
              Contact
            </Link>
          </NavigationMenuLink>
        </NavigationMenuList>
      </NavigationMenu>
      <div className="ml-auto flex gap-2">
        <Button variant="outline">Sign in</Button>
        <Button>Sign Up</Button>
      </div>
    </header>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
