import Image from "next/image"
export default function PatternLogo() {
    return (
        <div>
            <div className="flex">

                <div>
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                </div>
                <div>
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                </div>
                <div>
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                </div>
                <div>
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                </div>
                <div>
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                </div>
                <div>
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                </div>
                <div>
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                </div>
                <div>
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                </div>
                <div>
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                </div>
                <div>
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                </div>
                <div>
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                    <Image
                        src='/pattern.svg'
                        width={50}
                        height={500}
                        alt="pattern"
                    />
                </div>
            </div>
        </div>
    )
}